table olist_orders_dataset
	lineageTag: b3de5584-447c-4ad1-8625-8859cc20515e

	column order_id
		dataType: string
		lineageTag: 5d257fd7-fb66-4052-a978-4093f067db7a
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: e1fdaa74-ab62-456a-9b49-e44126d6fe20
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: 76f0d417-a678-455a-94bf-466fafed36e3
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column order_purchase_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 61b27a5a-8800-4d63-8dc4-10c150eeecb3
		summarizeBy: none
		sourceColumn: order_purchase_timestamp

		variation Variation
			isDefault
			relationship: c98067c7-77fb-43d5-949e-7486fa675a80
			defaultHierarchy: LocalDateTable_8ba65c18-652d-4b6b-a7bb-e62f1ef6dbb3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column order_approved_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 496a523c-d10e-45a6-be78-e213fed3531a
		summarizeBy: none
		sourceColumn: order_approved_at

		variation Variation
			isDefault
			relationship: 42307cd5-d0c3-47f3-996c-ba0ab6183d1c
			defaultHierarchy: LocalDateTable_b1cf5133-7caa-47ae-9781-640d5319f462.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column order_delivered_carrier_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 87a458fc-3a86-45db-895c-11cc24982c1f
		summarizeBy: none
		sourceColumn: order_delivered_carrier_date

		variation Variation
			isDefault
			relationship: d4416007-f463-4956-9d22-52482c8d1dd3
			defaultHierarchy: LocalDateTable_1503276f-75f2-48f7-8ff1-f2818c5687f6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column order_delivered_customer_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 86a40baf-cdee-4111-94e6-fb0adb10298b
		summarizeBy: none
		sourceColumn: order_delivered_customer_date

		variation Variation
			isDefault
			relationship: 131dd3ee-6117-4bd7-a617-d0e244f77a0a
			defaultHierarchy: LocalDateTable_3d84185b-c255-48e7-ab3b-f9b01f21dfc3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column order_estimated_delivery_date
		dataType: dateTime
		formatString: General Date
		lineageTag: e0fd8b70-d8f1-4ae6-ba1c-bab4b54e03a2
		summarizeBy: none
		sourceColumn: order_estimated_delivery_date

		variation Variation
			isDefault
			relationship: aeba3c44-5729-4b61-8f5b-ab7eada7eb16
			defaultHierarchy: LocalDateTable_ebf4f305-f516-43b7-ac85-2cb74a0b1221.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Ano_Mes
		dataType: string
		lineageTag: 347832f3-ccfc-490c-b13c-7995401be206
		summarizeBy: none
		sourceColumn: Ano_Mes

		annotation SummarizationSetBy = Automatic

	column Ano_Mes_Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2e297f9e-abfc-4568-a68d-6aafbbfb8e87
		summarizeBy: none
		sourceColumn: Ano_Mes_Data

		variation Variation
			isDefault
			relationship: cfc492bc-ccaf-4a5d-b8f7-2fff7b39b2a1
			defaultHierarchy: LocalDateTable_184d5616-43a2-4467-b988-31450a74264e.'Hierarquia de datas'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Lead_Time_Dias
		dataType: int64
		formatString: 0
		lineageTag: 9c582168-1999-442f-bfa2-cdc882ac5571
		summarizeBy: sum
		sourceColumn: Lead_Time_Dias

		annotation SummarizationSetBy = Automatic

	column Atrasado
		dataType: string
		lineageTag: a88fcaca-083f-49f9-842c-2246d16b02da
		summarizeBy: none
		sourceColumn: Atrasado

		annotation SummarizationSetBy = Automatic

	column Dias_Atraso
		dataType: int64
		formatString: 0
		lineageTag: 98148183-173e-4b5d-b6f4-508d0a80b552
		summarizeBy: sum
		sourceColumn: Dias_Atraso

		annotation SummarizationSetBy = Automatic

	partition olist_orders_dataset = m
		mode: import
		source = ```
				let
				    Fonte = Csv.Document(
				        File.Contents(Pasta & "olist_orders_dataset.csv"),
				        [Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]
				    ),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{
				        {"order_id", type text}, 
				        {"customer_id", type text}, 
				        {"order_status", type text}, 
				        {"order_purchase_timestamp", type datetime}, 
				        {"order_approved_at", type datetime}, 
				        {"order_delivered_carrier_date", type datetime}, 
				        {"order_delivered_customer_date", type datetime}, 
				        {"order_estimated_delivery_date", type datetime}
				    }),
				    #"Filtro Delivered" = Table.SelectRows(#"Tipo Alterado", each [order_status] = "delivered"),
				    #"Filtro Periodo" = Table.SelectRows(#"Filtro Delivered", each 
				        [order_purchase_timestamp] >= #datetime(2017, 1, 1, 0, 0, 0) and 
				        [order_purchase_timestamp] <= #datetime(2018, 8, 31, 23, 59, 59)
				    ),
				    #"Add Ano_Mes" = Table.AddColumn(#"Filtro Periodo", "Ano_Mes", each 
				        Date.ToText(DateTime.Date([order_purchase_timestamp]), "yyyy-MM"), 
				        type text
				    ),
				    #"Add Ano_Mes_Data" = Table.AddColumn(#"Add Ano_Mes", "Ano_Mes_Data", each 
				        Date.StartOfMonth(DateTime.Date([order_purchase_timestamp])), 
				        type date
				    ),
				    #"Add Lead_Time" = Table.AddColumn(#"Add Ano_Mes_Data", "Lead_Time_Dias", each 
				        if [order_delivered_customer_date] <> null 
				        then Duration.Days([order_delivered_customer_date] - [order_purchase_timestamp]) 
				        else null, 
				        Int64.Type
				    ),
				    #"Add Atrasado" = Table.AddColumn(#"Add Lead_Time", "Atrasado", each 
				        if [order_delivered_customer_date] <> null and [order_estimated_delivery_date] <> null 
				        then (if [order_delivered_customer_date] > [order_estimated_delivery_date] 
				              then "Atrasado" 
				              else "No Prazo") 
				        else null, 
				        type text
				    ),
				    #"Add Dias_Atraso" = Table.AddColumn(#"Add Atrasado", "Dias_Atraso", each 
				        if [order_delivered_customer_date] <> null and [order_estimated_delivery_date] <> null 
				        then Duration.Days([order_delivered_customer_date] - [order_estimated_delivery_date]) 
				        else null, 
				        Int64.Type
				    )
				in
				    #"Add Dias_Atraso"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

