table olist_order_reviews_dataset
	lineageTag: aaccd124-443f-48a7-8dc4-70cb36fe0940

	column review_id
		dataType: string
		lineageTag: 4dcd9d1c-05a9-4ce9-b34b-8cde8213a3ef
		summarizeBy: none
		sourceColumn: review_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: 7d04f242-9d1b-44fb-ba6c-39df87c1296a
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: 2fcd2c52-4b57-445e-971d-29e69adf6732
		summarizeBy: sum
		sourceColumn: review_score

		annotation SummarizationSetBy = Automatic

	column review_comment_title
		dataType: string
		lineageTag: 90020348-3076-4285-b38a-4d57511d2535
		summarizeBy: none
		sourceColumn: review_comment_title

		annotation SummarizationSetBy = Automatic

	column review_comment_message
		dataType: string
		lineageTag: 3165de04-ecfb-440d-82a4-58c292297206
		summarizeBy: none
		sourceColumn: review_comment_message

		annotation SummarizationSetBy = Automatic

	column review_creation_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d30a7c4e-9994-4f88-8a5f-b7fe3bb3a95f
		summarizeBy: none
		sourceColumn: review_creation_date

		variation Variation
			isDefault
			relationship: 65e0b495-37bc-4e42-8b2f-7c0c84a25fa7
			defaultHierarchy: LocalDateTable_164bc7b6-adb5-4989-a7ca-8313f5141cfd.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column review_answer_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 47435340-4371-4361-894b-ec8a0173aa6d
		summarizeBy: none
		sourceColumn: review_answer_timestamp

		variation Variation
			isDefault
			relationship: 07357d36-677a-42b2-b08f-025d9dd8d03a
			defaultHierarchy: LocalDateTable_14c414e7-40e0-423e-ba68-98be87b0344c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Faixa_Satisfacao
		dataType: string
		lineageTag: a8a5d0e8-02b3-4c0f-ab4f-a76f5c10dea9
		summarizeBy: none
		sourceColumn: Faixa_Satisfacao

		annotation SummarizationSetBy = Automatic

	partition olist_order_reviews_dataset = m
		mode: import
		source = ```
				let
				    Fonte = Csv.Document(File.Contents(Pasta&"olist_order_reviews_dataset.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"review_id", type text}, {"order_id", type text}, {"review_score", Int64.Type}, {"review_comment_title", type text}, {"review_comment_message", type text}, {"review_creation_date", type datetime}, {"review_answer_timestamp", type datetime}}),
				
				    // === COLUNA: Faixa_Satisfacao ===
				    #"Add Faixa" = Table.AddColumn(#"Tipo Alterado", "Faixa_Satisfacao", each 
				        if [review_score] >= 4 then "Satisfeito"
				        else if [review_score] = 3 then "Neutro"
				        else "Insatisfeito", 
				        type text
				    ),
				
				    // === FILTRAR: somente pedidos que existem em orders ===
				    #"Merge" = Table.NestedJoin(#"Add Faixa", {"order_id"}, olist_orders_dataset, {"order_id"}, "Orders", JoinKind.Inner),
				    #"Remover Coluna Merge" = Table.RemoveColumns(#"Merge", {"Orders"})
				
				in
				    #"Remover Coluna Merge"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

