table olist_geolocation_dataset
	lineageTag: 6fc5815b-4167-4158-aa5d-037948e6677c

	column geolocation_zip_code_prefix
		dataType: string
		lineageTag: 5c67804c-babc-4936-9fc7-ac30156d111c
		summarizeBy: none
		sourceColumn: geolocation_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column geolocation_lat
		dataType: double
		lineageTag: 6fc123c7-80d9-4eda-9524-128c1d060db0
		summarizeBy: sum
		sourceColumn: geolocation_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column geolocation_lng
		dataType: double
		lineageTag: 76122aaa-237f-4a1e-afce-cc52ac319c5d
		summarizeBy: sum
		sourceColumn: geolocation_lng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column geolocation_city
		dataType: string
		lineageTag: 0684290c-9fdd-4bac-bb3f-d3204882de03
		summarizeBy: none
		sourceColumn: geolocation_city

		annotation SummarizationSetBy = Automatic

	column geolocation_state
		dataType: string
		lineageTag: b78ae0ae-b9bd-4996-a919-c47d9dc234a5
		summarizeBy: none
		sourceColumn: geolocation_state

		annotation SummarizationSetBy = Automatic

	partition olist_geolocation_dataset = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(Pasta&"olist_geolocation_dataset.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Valor Substituído" = Table.ReplaceValue(#"Cabeçalhos Promovidos",".",",",Replacer.ReplaceText,{"geolocation_lat", "geolocation_lng"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Valor Substituído",{{"geolocation_zip_code_prefix", type text}, {"geolocation_lat", type number}, {"geolocation_lng", type number}, {"geolocation_city", type text}, {"geolocation_state", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

